apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rknpu-monitor
  namespace: observability  # <--- Put the Monitor where Prometheus lives
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - monitoring        # <--- Tell it to look in your custom namespace
  selector:
    matchLabels:
      app: rknpu-exporter # Matches the Service in the 'monitoring' namespace
  endpoints:
  - port: metrics
    interval: 10s