apiVersion: v1
kind: Service
metadata:
  name: rknpu-exporter-service
  namespace: monitoring
  labels:
    app: rknpu-exporter
spec:
  selector:
    name: rknpu-exporter # Matches the DaemonSet label
  ports:
    - protocol: TCP
      port: 9101
      targetPort: 9101
