apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rknpu-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      name: rknpu-exporter # <--- THIS MUST MATCH...
  template:
    metadata:
      labels:
        name: rknpu-exporter # <--- ...THIS EXACTLY
    spec:
      nodeSelector:
        hardware: npu
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: exporter
        image: ghcr.io/jallen2281/rknpu-monitoring:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: sys-kernel-debug
          mountPath: /sys/kernel/debug
          readOnly: true
        - name: sys-devfreq
          mountPath: /sys/class/devfreq
          readOnly: true
        - name: proc-mem
          mountPath: /proc/meminfo
          readOnly: true
      volumes:
      - name: sys-kernel-debug
        hostPath:
          path: /sys/kernel/debug
      - name: sys-devfreq
        hostPath:
          path: /sys/class/devfreq
      - name: proc-mem
        hostPath:
          path: /proc/meminfo

